baseURL = "https://sammyageil.com/"
languageCode = "en-us"
title = "Sammy Ageil"
theme="base16"
pygmentsUseClasses= false
pygmentsCodefences= true
pygmentStyle="base16-snazzy"

  [params]
customCss =   ["css/syntax.css"]
customJS  =   ["js/copybutton.js"]

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    # style = "base16-snazzy"
    tabWidth = 2

[taxonomies]
    category = "categories"
    tag = "tags"

